# Nome da aplicação
spring.application.name=livro-digital-de-receitas-andry

# Importa configurações locais, como credenciais do banco
spring.config.import=optional:classpath:application-local.properties

# Configuração do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Limites para upload de arquivos
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB